# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Shin Blog
    url: https://shin.is-a.dev
  - name: AnimeVsub
    url: https://animevsub.eu.org
  - name: Manga Raiku
    url: https://mangaraiku.eu.org
  - name: AnimeVsub API intro/outro
    url: https://opend-9animetv.animevsub.eu.org/list-episodes?name=Tonikaku+Kawaii
    icon: https://animevsub.eu.org/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  cname: shin.is-a.dev
  name: Tachibana Shin website status Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  baseUrl: /upptime
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
